name: muslim_launcher
description: A minimalist launcher to foster digital wellbeing.
publish_to: "none"
version: 1.0.0+1

isar_version: &isar_version 3.1.8 # define the version to be used

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Database
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.3

  # Networking & Audio
  dio: ^5.4.3+1
  just_audio: ^0.9.38

  # Device & App Utilities
  installed_apps: ^1.6.0
  usage_stats: ^1.3.1
  external_app_launcher: ^4.0.3

  # Background Processing & Notifications
  flutter_background_service: ^5.0.1
  flutter_local_notifications: ^17.1.2

  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  flutter_launcher_icons: "^0.13.1"

# Konfigurasi untuk flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false # Tidak membuat untuk iOS
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
