---
name: Build APK on Dev Branch

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Build APK
        run: flutter build apk --release

      - name: Verify APK exists
        run: |
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "APK file not found!"
            exit 1
          fi
          ls -la build/app/outputs/flutter-apk/

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release and Upload APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="dev-build-${{ steps.date.outputs.date }}"
          RELEASE_NAME="Dev Build ${{ steps.date.outputs.date }}"
          APK_NAME="muslim-launcher-dev-${{ steps.date.outputs.date }}.apk"

          # Create release with the APK
          gh release create "$TAG_NAME" \
            --title "$RELEASE_NAME" \
            --notes "Automated build from dev branch
          Commit: ${{ github.sha }}
          Build Date: ${{ steps.date.outputs.date }}" \
            --prerelease \
            build/app/outputs/flutter-apk/app-release.apk#"$APK_NAME"